
Vagrant.configure("2") do |config|
    config.vm.box = "mghalbi/docker-centos9-ansible"
  
    # Provisioning configuration for Ansible.
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
    end
  end
